  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - UMASK=022 #optional
    volumes:
      - ./volumes/sonarr/data:/config
      - ./media:/media
    ports:
      - 8989:8989
    restart: unless-stopped
