  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/lidarr/config:/config
      - ./media:/media
    ports:
      - 8686:8686
