  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Moscow
      - UMASK=022 #optional
    volumes:
      - ./volumes/radarr/config:/config
      - ./media:/media
    ports:
      - 7878:7878
    restart: unless-stopped
